#4.1 Exercise on Functions

Task 1: Create a Python program that converts between different units of measurement.


In [ ]:
def convert_units(choice, value):
    """Convert value between supported measurement units."""

    if choice == "1":
        return value*3.28084          # m → ft
    elif choice == "2":
        return value/3.28084          # ft → m
    elif choice == "3":
        return value*2.20462          # kg → lbs
    elif choice == "4":
        return value/2.20462          # lbs → kg
    elif choice == "5":
        return value*0.264172         # L → gal
    elif choice == "6":
        return value/0.264172         # gal → L
    else:
        return None


def unit_conversion():
    print("1. m→ft  2. ft→m  3. kg→lbs  4. lbs→kg  5. L→gal  6. gal→L")
    choice = input("Choose conversion: ")

    try:
        value= float(input("Enter value: "))
        result= convert_units(choice, value)

        if result is None:
            print("Unsupported conversion.")
        else:
            print("Result:", round(result, 4))

    except ValueError:
        print("Invalid numeric input.")


unit_conversion()

1. m→ft  2. ft→m  3. kg→lbs  4. lbs→kg  5. L→gal  6. gal→L
Choose conversion: 2
Enter value: 45
Result: 13.716


Task 2: Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
import builtins

def find_sum(nums):
    """Return sum of numbers."""
    return builtins.sum(nums) # Explicitly use the built-in sum

def find_average(nums):
    """Return average of numbers."""
    return builtins.sum(nums) / len(nums) # Explicitly use the built-in sum

def find_maximum(nums):
    """Return maximum number."""
    return builtins.max(nums) # Explicitly use the built-in max

def find_minimum(nums):
    """Return minimum number."""
    return builtins.min(nums) # Explicitly use the built-in min


def math_operations_program():
    print("1.Sum  2.Average  3.Maximum  4.Minimum")
    choice = input("Choose operation: ")

    try:
        data = input("Enter numbers: ").strip()
        if not data:
            print("List cannot be empty.")
            return

        nums = list(map(float, data.split()))

        if choice == "1":
            print("Result:", find_sum(nums))
        elif choice == "2":
            print("Result:", find_average(nums))
        elif choice == "3":
            print("Result:", find_maximum(nums))
        elif choice == "4":
            print("Result:", find_minimum(nums))
        else:
            print("Invalid operation.")

    except ValueError:
        print("Invalid numeric input.")


math_operations_program()

1.Sum  2.Average  3.Maximum  4.Minimum
Choose operation: 1
Enter numbers: 10 20 30 40
Result: 100.0


#4.2 Exercise on List Manipulation:

1. Extract Every Other Element

In [ ]:
def extract_every_other(lst):
    """Return every other element starting from the first."""
    return lst[::2]

# Example
print(extract_every_other([1, 2, 3, 4, 5, 6]))  # [1, 3, 5]

[1, 3, 5]


2. Slice a Sublist (inclusive end)

In [ ]:
def get_sublist(lst, start, end):
    """Return sublist from start to end (inclusive)."""
    return lst[start:end+1]

# Example
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # [3, 4, 5]

[3, 4, 5]


3. Reverse a List Using Slicing

In [ ]:
def reverse_list(lst):
    """Return reversed list."""
    return lst[::-1]

# Example
print(reverse_list([1, 2, 3, 4, 5]))  # [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


4. Remove First and Last Elements

In [ ]:
def remove_first_last(lst):
    """Return list without first and last elements."""
    return lst[1:-1]

# Example
print(remove_first_last([1, 2, 3, 4, 5]))  # [2, 3, 4]

[2, 3, 4]


5. Get First n Elements

In [ ]:
def get_first_n(lst, n):
    """Return first n elements."""
    return lst[:n]

# Example
print(get_first_n([1, 2, 3, 4, 5], 3))  # [1, 2, 3]

[1, 2, 3]


6. Get Last n Elements

In [ ]:
def get_last_n(lst, n):
    """Return last n elements."""
    return lst[-n:]

# Example
print(get_last_n([1, 2, 3, 4, 5], 2))  # [4, 5]

[4, 5]


7. Reverse Skip Elements

In [ ]:
def reverse_skip(lst):
    """Return every second element from second-last in reverse."""
    return lst[-2::-2]

# Example
print(reverse_skip([1, 2, 3, 4, 5, 6]))  # [5, 3, 1]

[5, 3, 1]


#4.3 Exercise on Nested List:

1.Flatten a Nested List:

In [ ]:
def flatten(lst):
    """Flatten a nested list by one level."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(item)
        else:
            result.append(item)
    return result

# Example
print(flatten([[1, 2], [3, 4], [5]]))  # [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


2. Access Nested List Element

In [ ]:
def access_nested_element(lst, indices):
    """Return element at the given nested indices."""
    item = lst
    for i in indices:
        item = item[i]
    return item

# Example
lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst, [1, 2]))  # 6

6


3. Sum of All Elements in Nested List

In [ ]:
def sum_nested(lst):
    """Return sum of all elements in nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Example
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # 21

21


4. Remove Specific Element from Nested List

In [ ]:
def remove_element(lst, elem):
    """Remove all occurrences of elem from nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

# Example
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # [[1], [3], [4, 5]]

[[1], [3], [4, 5]]


5. Find Maximum Element in Nested List

In [ ]:
def find_max(lst):
    """Return maximum element in nested list."""
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

# Example
print(find_max([[1, 2], [3, [4, 5]], 6]))  # 6

6


6. Count Occurrences in Nested List

In [ ]:
def count_occurrences(lst, elem):
    """Count occurrences of elem in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Example
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # 3

3


7. Deep Flatten (any depth)

In [ ]:
def deep_flatten(lst):
    """Flatten list regardless of nesting depth."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# Example
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
# [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [ ]:
def average_nested(lst):
    """Return average of all elements in nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

# Example
print(average_nested([[1, 2], [3, 4], [5, 6]]))  # 3.5

3.5



---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


##Problem 1: Array Creation (NumPy)

###1. Initialize an empty array with size 2×2

In [ ]:
import numpy as np

arr_empty = np.empty((2, 2))
print(arr_empty)

[[9.67986363e-316 0.00000000e+000]
 [6.37114106e-067 2.73785467e-052]]


###2. Initialize an all-ones array with size 4×2

In [ ]:
arr_ones = np.ones((4, 2))
print(arr_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


###3. Return a new array of given shape and type, filled with a fill value

In [ ]:
arr_full = np.full((3, 3), fill_value=7, dtype=int)
print(arr_full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


###4. Return a new array of zeros with same shape and type as a given array

In [ ]:
base_array = np.array([[1, 2, 3], [4, 5, 6]])

arr_zeros_like = np.zeros_like(base_array)
print(arr_zeros_like)

[[0 0 0]
 [0 0 0]]


###5. Return a new array of ones with same shape and type as a given array

In [ ]:
arr_ones_like = np.ones_like(base_array)
print(arr_ones_like)

[[1 1 1]
 [1 1 1]]


###6. Convert an existing list to a NumPy array

In [ ]:
new_list= [1, 2, 3, 4]

arr_from_list = np.array(new_list)
print(arr_from_list)

[1 2 3 4]


##Problem 2: Array Manipulation: Numerical Ranges & Indexing

####1. Create an array with values ranging from 10 to 49

In [ ]:
import numpy as np

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


####2. Create a 3×3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


####3. Create a 3×3 identity matrix

In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


####4. Create a random array of size 30 and find the mean

In [ ]:
rand_arr = np.random.random(30)
mean_val = rand_arr.mean()

print(rand_arr)
print("Mean:", mean_val)

[4.68402519e-01 8.85986771e-01 3.82981317e-01 7.33692645e-01
 4.01199088e-01 4.07589410e-01 4.13658541e-02 4.12256392e-01
 5.26703656e-01 2.35372270e-01 3.45233952e-01 7.95607381e-02
 1.95948841e-01 8.36204191e-01 2.62756974e-01 2.62182968e-01
 6.24369561e-01 7.56212336e-01 5.76221191e-01 1.66642761e-01
 9.20842080e-01 9.11175647e-01 3.36311603e-04 8.13207934e-01
 6.31646056e-01 3.54521582e-01 1.28836669e-01 5.77592199e-01
 7.83970860e-01 8.66889396e-01]
Mean: 0.48633007230361686


5. Create a 10×10 array with random values and find min & max

In [ ]:
rand_matrix = np.random.random((10, 10))

print(rand_matrix)
print("Minimum:", rand_matrix.min())
print("Maximum:", rand_matrix.max())

[[0.65971415 0.5498647  0.72941068 0.25806575 0.58585547 0.07887172
  0.32772161 0.13913618 0.84419906 0.35621395]
 [0.03488755 0.30455309 0.820009   0.70475534 0.86768846 0.03371293
  0.02560781 0.65365179 0.39531609 0.41693357]
 [0.26172692 0.90296276 0.27736246 0.66835211 0.81804214 0.78708617
  0.90266934 0.55960246 0.50739075 0.3209936 ]
 [0.3946155  0.9895104  0.56396176 0.24354436 0.41475967 0.31546452
  0.20845834 0.2003588  0.99119716 0.30444888]
 [0.62290996 0.68636738 0.3473652  0.54432313 0.11397667 0.39612201
  0.27270037 0.69391598 0.96233591 0.79929833]
 [0.30312468 0.44581423 0.84240723 0.82569526 0.92929837 0.140736
  0.41082267 0.65855443 0.71510572 0.06702696]
 [0.4060234  0.14645251 0.85055936 0.87564355 0.76533254 0.68989929
  0.36811678 0.48835519 0.4327369  0.16122624]
 [0.56212648 0.79688525 0.23367684 0.89538037 0.91343587 0.4077539
  0.34662543 0.96143743 0.37574976 0.85285678]
 [0.91862641 0.35781003 0.15825097 0.99880944 0.96625288 0.55985779
  0.79602077 0.

####6. Create a zero array of size 10 and replace 5th element with 1

In [ ]:
arr = np.zeros(10)
arr[4] = 1   # index starts from 0

print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


####7. Reverse an array

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

print(reversed_arr)

[0 4 0 0 2 1]


####8. Create a 2D array with 1 on border and 0 inside

In [ ]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


####9. Create an 8×8 checkerboard matrix

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


###Problem 3: Array Operations
###For the following arrays:
###x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
###v = np.array([9,10]) and w = np.array([11,12]);

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

###1. Add the two arrays

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
add_xy = x + y
print(add_xy)

[[ 6  8]
 [10 13]]


###2. Subtract the two arrays

In [ ]:
sub_xy = x-y
print(sub_xy)

[[-4 -4]
 [-4 -3]]


###3. Multiply the arrays with any integer

In [ ]:
mul_x = x * 3
mul_y = y * 2

print(mul_x)
print(mul_y)

[[ 3  6]
 [ 9 15]]
[[10 12]
 [14 16]]


###4. Square each element of the arrays

In [ ]:
sq_x = x ** 2
sq_y = y ** 2

print(sq_x)
print(sq_y)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]


###5. Dot Products

####a) v · w

In [ ]:
dot_vw = np.dot(v, w)
print(dot_vw)

219


####b) x · v

In [ ]:
dot_xv = np.dot(x, v)
print(dot_xv)

[29 77]


####c) x · y

In [ ]:
dot_xy = np.dot(x, y)
print(dot_xy)

[[19 22]
 [50 58]]


###6. Concatenation

###a) Concatenate x and y along rows

In [ ]:
concat_rows = np.concatenate((x, y), axis=0)
print(concat_rows)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


###b) Concatenate v and w along columns

In [ ]:
concat_cols = np.column_stack((v, w))
print(concat_cols)

[[ 9 11]
 [10 12]]


###7. Concatenate x and v

In [ ]:
x = np.array([[1, 2],
              [3, 5]])
v = np.array([9, 10])

v_row = v.reshape(1, 2)          # convert to 2D row
result = np.concatenate((x, v_row), axis=0)

print(result)

[[ 1  2]
 [ 3  5]
 [ 9 10]]


The error occurred because the two arrays have different dimensions. Array x is a 2D matrix with shape (2, 2), while array v is a 1D array with shape (2,). NumPy can only concatenate arrays that have the same number of dimensions and compatible shapes along the chosen axis. Since a 2D array (rows and columns) cannot be directly combined with a 1D array (a flat list), NumPy raises a dimension mismatch error. Converting v into a 2D array using reshape() fixes the issue.

In [ ]:
x = np.array([[1, 2],
              [3, 5]])
v = np.array([9, 10])

v_row = v.reshape(1, 2)          # convert to 2D row
result = np.concatenate((x, v_row), axis=0)

print(result)

#Problem 4: Matrix Operations

##Given Matrices

In [ ]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

###1. Prove A · A⁻¹ = I

In [ ]:
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A · A_inv:\n", I)

###2. Prove AB ≠ BA

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

###3. Prove (AB)ᵀ = BᵀAᵀ

In [ ]:
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)

#System of Linear Equations
###Given:

###Step 1: Convert to Matrix Form (AX = B)

In [ ]:
A = np.array([[ 2, -3,  1],
              [ 1, -1,  2],
              [ 3,  1, -1]])

B = np.array([-1, -3, 9])

###Step 2: Solve using Inverse Method
####Formula:
####X = A⁻¹B

In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution [x y z]:\n", X)

###Step 3: Solve directly using NumPy linear algebra

In [ ]:
X = np.linalg.solve(A, B)
print("Solution [x y z]:\n", X)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')